/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArboristConsultationRouteImport } from './routes/arborist-consultation'
import { Route as CablingBracingRouteImport } from './routes/cabling-bracing'
import { Route as CommercialTreeServiceRouteImport } from './routes/commercial-tree-service'
import { Route as EmergencyTreeServiceRouteImport } from './routes/emergency-tree-service'
import { Route as FreeQuoteRouteImport } from './routes/free-quote'
import { Route as LotClearingRouteImport } from './routes/lot-clearing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as StumpGrindingRouteImport } from './routes/stump-grinding'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TreeRemovalRouteImport } from './routes/tree-removal'
import { Route as TreeRemovalCostRouteImport } from './routes/tree-removal-cost'
import { Route as TreeTrimmingRouteImport } from './routes/tree-trimming'
import { Route as WhatToExpectRouteImport } from './routes/what-to-expect'
import { Route as ApiLeadRouteImport } from './routes/api/lead'
import { Route as LpTreeRemovalRouteImport } from './routes/lp/tree-removal'
import { Route as RecentWorkIndexRouteImport } from './routes/recent-work/index'
import { Route as RecentWorkSlugRouteImport } from './routes/recent-work/$slug'
import { Route as TreeServiceCityRouteImport } from './routes/tree-service/$city'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArboristConsultationRoute = ArboristConsultationRouteImport.update({
  id: '/arborist-consultation',
  path: '/arborist-consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const CablingBracingRoute = CablingBracingRouteImport.update({
  id: '/cabling-bracing',
  path: '/cabling-bracing',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialTreeServiceRoute = CommercialTreeServiceRouteImport.update({
  id: '/commercial-tree-service',
  path: '/commercial-tree-service',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyTreeServiceRoute = EmergencyTreeServiceRouteImport.update({
  id: '/emergency-tree-service',
  path: '/emergency-tree-service',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeQuoteRoute = FreeQuoteRouteImport.update({
  id: '/free-quote',
  path: '/free-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const LotClearingRoute = LotClearingRouteImport.update({
  id: '/lot-clearing',
  path: '/lot-clearing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const StumpGrindingRoute = StumpGrindingRouteImport.update({
  id: '/stump-grinding',
  path: '/stump-grinding',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeRemovalRoute = TreeRemovalRouteImport.update({
  id: '/tree-removal',
  path: '/tree-removal',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeRemovalCostRoute = TreeRemovalCostRouteImport.update({
  id: '/tree-removal-cost',
  path: '/tree-removal-cost',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeTrimmingRoute = TreeTrimmingRouteImport.update({
  id: '/tree-trimming',
  path: '/tree-trimming',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatToExpectRoute = WhatToExpectRouteImport.update({
  id: '/what-to-expect',
  path: '/what-to-expect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadRoute = ApiLeadRouteImport.update({
  id: '/api/lead',
  path: '/api/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const LpTreeRemovalRoute = LpTreeRemovalRouteImport.update({
  id: '/lp/tree-removal',
  path: '/lp/tree-removal',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentWorkIndexRoute = RecentWorkIndexRouteImport.update({
  id: '/recent-work/',
  path: '/recent-work/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentWorkSlugRoute = RecentWorkSlugRouteImport.update({
  id: '/recent-work/$slug',
  path: '/recent-work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeServiceCityRoute = TreeServiceCityRouteImport.update({
  id: '/tree-service/$city',
  path: '/tree-service/$city',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arborist-consultation': typeof ArboristConsultationRoute
  '/cabling-bracing': typeof CablingBracingRoute
  '/commercial-tree-service': typeof CommercialTreeServiceRoute
  '/emergency-tree-service': typeof EmergencyTreeServiceRoute
  '/free-quote': typeof FreeQuoteRoute
  '/lot-clearing': typeof LotClearingRoute
  '/privacy': typeof PrivacyRoute
  '/stump-grinding': typeof StumpGrindingRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/tree-removal': typeof TreeRemovalRoute
  '/tree-removal-cost': typeof TreeRemovalCostRoute
  '/tree-trimming': typeof TreeTrimmingRoute
  '/what-to-expect': typeof WhatToExpectRoute
  '/api/lead': typeof ApiLeadRoute
  '/lp/tree-removal': typeof LpTreeRemovalRoute
  '/recent-work/$slug': typeof RecentWorkSlugRoute
  '/tree-service/$city': typeof TreeServiceCityRoute
  '/recent-work/': typeof RecentWorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arborist-consultation': typeof ArboristConsultationRoute
  '/cabling-bracing': typeof CablingBracingRoute
  '/commercial-tree-service': typeof CommercialTreeServiceRoute
  '/emergency-tree-service': typeof EmergencyTreeServiceRoute
  '/free-quote': typeof FreeQuoteRoute
  '/lot-clearing': typeof LotClearingRoute
  '/privacy': typeof PrivacyRoute
  '/stump-grinding': typeof StumpGrindingRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/tree-removal': typeof TreeRemovalRoute
  '/tree-removal-cost': typeof TreeRemovalCostRoute
  '/tree-trimming': typeof TreeTrimmingRoute
  '/what-to-expect': typeof WhatToExpectRoute
  '/api/lead': typeof ApiLeadRoute
  '/lp/tree-removal': typeof LpTreeRemovalRoute
  '/recent-work/$slug': typeof RecentWorkSlugRoute
  '/tree-service/$city': typeof TreeServiceCityRoute
  '/recent-work': typeof RecentWorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arborist-consultation': typeof ArboristConsultationRoute
  '/cabling-bracing': typeof CablingBracingRoute
  '/commercial-tree-service': typeof CommercialTreeServiceRoute
  '/emergency-tree-service': typeof EmergencyTreeServiceRoute
  '/free-quote': typeof FreeQuoteRoute
  '/lot-clearing': typeof LotClearingRoute
  '/privacy': typeof PrivacyRoute
  '/stump-grinding': typeof StumpGrindingRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/tree-removal': typeof TreeRemovalRoute
  '/tree-removal-cost': typeof TreeRemovalCostRoute
  '/tree-trimming': typeof TreeTrimmingRoute
  '/what-to-expect': typeof WhatToExpectRoute
  '/api/lead': typeof ApiLeadRoute
  '/lp/tree-removal': typeof LpTreeRemovalRoute
  '/recent-work/$slug': typeof RecentWorkSlugRoute
  '/tree-service/$city': typeof TreeServiceCityRoute
  '/recent-work/': typeof RecentWorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arborist-consultation'
    | '/cabling-bracing'
    | '/commercial-tree-service'
    | '/emergency-tree-service'
    | '/free-quote'
    | '/lot-clearing'
    | '/privacy'
    | '/stump-grinding'
    | '/terms'
    | '/thank-you'
    | '/tree-removal'
    | '/tree-removal-cost'
    | '/tree-trimming'
    | '/what-to-expect'
    | '/api/lead'
    | '/lp/tree-removal'
    | '/recent-work/$slug'
    | '/tree-service/$city'
    | '/recent-work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arborist-consultation'
    | '/cabling-bracing'
    | '/commercial-tree-service'
    | '/emergency-tree-service'
    | '/free-quote'
    | '/lot-clearing'
    | '/privacy'
    | '/stump-grinding'
    | '/terms'
    | '/thank-you'
    | '/tree-removal'
    | '/tree-removal-cost'
    | '/tree-trimming'
    | '/what-to-expect'
    | '/api/lead'
    | '/lp/tree-removal'
    | '/recent-work/$slug'
    | '/tree-service/$city'
    | '/recent-work'
  id:
    | '__root__'
    | '/'
    | '/arborist-consultation'
    | '/cabling-bracing'
    | '/commercial-tree-service'
    | '/emergency-tree-service'
    | '/free-quote'
    | '/lot-clearing'
    | '/privacy'
    | '/stump-grinding'
    | '/terms'
    | '/thank-you'
    | '/tree-removal'
    | '/tree-removal-cost'
    | '/tree-trimming'
    | '/what-to-expect'
    | '/api/lead'
    | '/lp/tree-removal'
    | '/recent-work/$slug'
    | '/tree-service/$city'
    | '/recent-work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArboristConsultationRoute: typeof ArboristConsultationRoute
  CablingBracingRoute: typeof CablingBracingRoute
  CommercialTreeServiceRoute: typeof CommercialTreeServiceRoute
  EmergencyTreeServiceRoute: typeof EmergencyTreeServiceRoute
  FreeQuoteRoute: typeof FreeQuoteRoute
  LotClearingRoute: typeof LotClearingRoute
  PrivacyRoute: typeof PrivacyRoute
  StumpGrindingRoute: typeof StumpGrindingRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  TreeRemovalRoute: typeof TreeRemovalRoute
  TreeRemovalCostRoute: typeof TreeRemovalCostRoute
  TreeTrimmingRoute: typeof TreeTrimmingRoute
  WhatToExpectRoute: typeof WhatToExpectRoute
  ApiLeadRoute: typeof ApiLeadRoute
  LpTreeRemovalRoute: typeof LpTreeRemovalRoute
  RecentWorkSlugRoute: typeof RecentWorkSlugRoute
  TreeServiceCityRoute: typeof TreeServiceCityRoute
  RecentWorkIndexRoute: typeof RecentWorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arborist-consultation': {
      id: '/arborist-consultation'
      path: '/arborist-consultation'
      fullPath: '/arborist-consultation'
      preLoaderRoute: typeof ArboristConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabling-bracing': {
      id: '/cabling-bracing'
      path: '/cabling-bracing'
      fullPath: '/cabling-bracing'
      preLoaderRoute: typeof CablingBracingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial-tree-service': {
      id: '/commercial-tree-service'
      path: '/commercial-tree-service'
      fullPath: '/commercial-tree-service'
      preLoaderRoute: typeof CommercialTreeServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-tree-service': {
      id: '/emergency-tree-service'
      path: '/emergency-tree-service'
      fullPath: '/emergency-tree-service'
      preLoaderRoute: typeof EmergencyTreeServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-quote': {
      id: '/free-quote'
      path: '/free-quote'
      fullPath: '/free-quote'
      preLoaderRoute: typeof FreeQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lot-clearing': {
      id: '/lot-clearing'
      path: '/lot-clearing'
      fullPath: '/lot-clearing'
      preLoaderRoute: typeof LotClearingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stump-grinding': {
      id: '/stump-grinding'
      path: '/stump-grinding'
      fullPath: '/stump-grinding'
      preLoaderRoute: typeof StumpGrindingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree-removal': {
      id: '/tree-removal'
      path: '/tree-removal'
      fullPath: '/tree-removal'
      preLoaderRoute: typeof TreeRemovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree-removal-cost': {
      id: '/tree-removal-cost'
      path: '/tree-removal-cost'
      fullPath: '/tree-removal-cost'
      preLoaderRoute: typeof TreeRemovalCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree-trimming': {
      id: '/tree-trimming'
      path: '/tree-trimming'
      fullPath: '/tree-trimming'
      preLoaderRoute: typeof TreeTrimmingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-to-expect': {
      id: '/what-to-expect'
      path: '/what-to-expect'
      fullPath: '/what-to-expect'
      preLoaderRoute: typeof WhatToExpectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead': {
      id: '/api/lead'
      path: '/api/lead'
      fullPath: '/api/lead'
      preLoaderRoute: typeof ApiLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/tree-removal': {
      id: '/lp/tree-removal'
      path: '/lp/tree-removal'
      fullPath: '/lp/tree-removal'
      preLoaderRoute: typeof LpTreeRemovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent-work/': {
      id: '/recent-work/'
      path: '/recent-work'
      fullPath: '/recent-work/'
      preLoaderRoute: typeof RecentWorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent-work/$slug': {
      id: '/recent-work/$slug'
      path: '/recent-work/$slug'
      fullPath: '/recent-work/$slug'
      preLoaderRoute: typeof RecentWorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree-service/$city': {
      id: '/tree-service/$city'
      path: '/tree-service/$city'
      fullPath: '/tree-service/$city'
      preLoaderRoute: typeof TreeServiceCityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArboristConsultationRoute: ArboristConsultationRoute,
  CablingBracingRoute: CablingBracingRoute,
  CommercialTreeServiceRoute: CommercialTreeServiceRoute,
  EmergencyTreeServiceRoute: EmergencyTreeServiceRoute,
  FreeQuoteRoute: FreeQuoteRoute,
  LotClearingRoute: LotClearingRoute,
  PrivacyRoute: PrivacyRoute,
  StumpGrindingRoute: StumpGrindingRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  TreeRemovalRoute: TreeRemovalRoute,
  TreeRemovalCostRoute: TreeRemovalCostRoute,
  TreeTrimmingRoute: TreeTrimmingRoute,
  WhatToExpectRoute: WhatToExpectRoute,
  ApiLeadRoute: ApiLeadRoute,
  LpTreeRemovalRoute: LpTreeRemovalRoute,
  RecentWorkSlugRoute: RecentWorkSlugRoute,
  TreeServiceCityRoute: TreeServiceCityRoute,
  RecentWorkIndexRoute: RecentWorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
